import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "next-themes"
import { BackgroundBeams } from "@/components/ui/background-beams";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({  children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en" className="dark">
      <body>
        <ThemeProvider attribute="class" forcedTheme="dark" enableSystem={false}>
          <div className="relative min-h-screen">
            {children}
            <BackgroundBeams />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}

